# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'CentOSAgent-TnT-Demo-Pool'

stages:
- stage: Test_Stage
  displayName: Test Stage
  jobs:
  - job: Test_Job
    displayName: Test Job
    steps:
    - script: echo 'SonarCube Result!'
      displayName: 'SonarCube Scan'


- stage: Deploy_Stage
  displayName: Deploy Stage
  jobs:
  - job: Deploy_Job
    displayName: Deploy Job
    steps:
    - task: Bash@3
      displayName: 'Clone Deployment Scripts'
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          if [ ! -d "t-and-t-demo" ]
          then
            git clone https://supermarioworld:$(repos-pat)@dev.azure.com/supermarioworld/t-and-t-demo/_git/t-and-t-demo
          else
            echo 'Add git pull here'
          fi
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'tnt-demo-ssh'
        sourceFolder: '$(Agent.BuildDirectory)/s/t-and-t-demo/deply-scripts/'
        contents: '**'
        targetFolder: '/home/mariuszdotnet/deply-scripts/'
        readyTimeout: '20000'