# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'CentOSAgent-TnT-Demo-Pool'

# resources:
#   repositories:
#   - repository: MyAzureReposGitRepo
#     type: git
#     name: t-and-t-demo/t-and-t-demo

# Test Staging
stages:
- stage: Test_Staging
  displayName: Test Staging
  jobs:
  - job: Test_Job
    displayName: Test Job
    steps:
    - checkout: self
    - script: echo 'SonarCube Result!'
      displayName: 'SonarCube Scan'

# Deploy to Staging
- stage: Deploy_Staging
  displayName: Deploy Staging
  jobs:
  - deployment: Deploy_Job
    displayName: Deploy Job
    #environment: 'staging'
    strategy:
      runOnce:
        deploy:      
          steps:
          - checkout: self
          - checkout: git://t-and-t-demo/t-and-t-demo
          - task: CopyFilesOverSSH@0
            displayName: 'SSH Deploy Scripts to Backend'
            inputs:
              sshEndpoint: 'tnt-demo-ssh'
              sourceFolder: '$(Agent.BuildDirectory)/s/t-and-t-demo/deploy-scripts/'
              contents: '**'
              targetFolder: '/home/mariuszdotnet/deploy-scripts/'
              readyTimeout: '20000'
          - task: SSH@0
            displayName: '1 Enable Maintenance'
            inputs:
              sshEndpoint: 'tnt-demo-ssh'
              runOptions: 'script'
              scriptPath: '/home/mariuszdotnet/deploy-scripts/1_enable_maintenance.sh'
              readyTimeout: '20000'
          - task: SSH@0
            displayName: '2 Backup Database'
            inputs:
              sshEndpoint: 'tnt-demo-ssh'
              runOptions: 'script'
              scriptPath: '/home/mariuszdotnet/deploy-scripts/2_backup_db.sh'
              readyTimeout: '20000'

          - task: SSH@0
            displayName: '7 Check Page Status 200'
            inputs:
              sshEndpoint: 'tnt-demo-ssh'
              runOptions: 'script'
              scriptPath: '/home/mariuszdotnet/deploy-scripts/7_check_200.sh'
              args: 'https://www.tntnightmarket.biz'
              readyTimeout: '20000'

# Deploy to Production
- stage: Deploy_Production
  displayName: Deploy Production
  jobs:
  - deployment: Deploy_Job
    displayName: Deploy Job
    #environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - checkout: git://t-and-t-demo/t-and-t-demo
            - script: echo 'Production Deployment Completed!'
              displayName: 'Production Deployment'