# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'CentOSAgent-TnT-Demo-Pool'

stages:
- stage: Build_and_Test_Stage
  jobs:
  - job: BuildJob
    steps:
    - task: Bash@3
      displayName: 'Clone Deploy Scripts'
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          if [ ! -d "t-and-t-demo" ]
          then
            git clone https://supermarioworld:$(repos-pat)@dev.azure.com/supermarioworld/t-and-t-demo/_git/t-and-t-demo
          else
            echo 'Add git pull here'
          fi

    - script: echo 'SonarCube Result!'
      displayName: 'SonarCube Scan'

- stage: Deploy_Stage
  jobs:
  - job: DeployJob
