# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'CentOSAgent-TnT-Demo-Pool'

steps:
- task: Bash@3
  displayName: 'Clone Deploy Scripts'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      git clone https://supermarioworld:$REPOS-PAT@dev.azure.com/supermarioworld/t-and-t-demo/_git/t-and-t-demo

- script: echo 'SonarCube Result!'
  displayName: 'SonarCube Scan'

- script: echo Hello, world!
  displayName: 'Run a one-line script'